
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Common Node.js Package

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
  

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.3.2
        id: installgitversion
        with:
          versionSpec: '6.6.x'
          preferLatestVersion: true
      - name: Determine version using GitVersion
        uses: gittools/actions/gitversion/execute@v4.3.2
        id: gitversion
      - name: Set npm package version from GitVersion
        run: |
          echo "Setting package.json version to ${{ steps.gitversion.outputs.FullSemVer }}"
          npm version "${{ steps.gitversion.outputs.FullSemVer }}" --no-git
        env:
          NODE_AUTH_TOKEN: ${{secrets.GIT_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
